### ISSUE TITLE
Bug: Editor closes / crashes unexpectedly

### ISSUE THREAD

**Issue by Noldorion** [GlowPuff/ICEditor#1]
I found two instances where the editor crashed / closed unexpectedly and I was able to reproduce it.

- One, enemy groups: When I try to add an enemy group without having a deployment point selected, the editor crashes.
- Two, "Modify variable" event action: When I click on "Add new trigger", and then on "Cancel" to get back to the previous window, the editor crashes.

**Comment by GlowPuff** [comment]
Fixed - and the second issue could possibly rear its head in other dialogs where you can create a Trigger before using it.
