### ISSUE TITLE
Bug: Trigger & Event counter not working properly

### ISSUE THREAD

**Issue by Noldorion** [GlowPuff/ICEditor#10]
Very minor, but just to be thorough:

The "Properties" screen always shows 1 additional Trigger and Event in the counter. For example, section 2 is empty, but is shown as having both 1 trigger and 1 event. The start section has 8 triggers and 14 events, but is shown as having 9 / 15.

![Trigger+Event Count](https://user-images.githubusercontent.com/67169098/149657159-7ff10901-eb2e-4b1b-b558-6c92f62e44e7.jpg)

**Comment by GlowPuff** [comment]
This is actually normal - it's including the "None" items.  I've updated the UI to reflect this addition.
