### ISSUE TITLE
Redeployment prevention bug

### ISSUE THREAD

**Issue by Noldorion** [GlowPuff/ICEditor#15]
Found by Marty:

Found by Marty:
“I may have encountered what I consider a bug.

I am trying to restrict 2 enemy groups from being able to be redeployed, and yet it keeps happening. This is what I have in place:
- I have the enemy groups' "Can be Redeployment" setting unflagged
- I have enemy groups also banned in the Banned Enemy Groups
- The 2 enemy groups are reserved and only appear as the result of an event

My current working theory is due to the nature of the mission, a highlight is used and clicked to note if the enemy group was defeated or sedated (brought to 1 health), then based on the result, a different variable is triggered and an event action is used to remove the group. My suspicion is that removing the group via an event action somehow disqualifies it from being defeated, and so it ends up circumventing the no redeployment logic, and gets deployed anyway.

I would love for this to be confirmed. Potentially, I could work around this by instructing the player to defeat the enemy group, which triggers an action to make as sedated or defeated, and then kicking off the variable. Just curious what others see.”

**Comment by GlowPuff** [comment]
Definitely a bug!  Looks like I was adding the group back to the Hand without checking the redeployment flag when the Remove Group Event Action fired, similar to your theory.  It also wasn't adding the group to the "cannot redeploy" list, if necessary.  Wow, glad you found this.  If I recall, the redeployment flag was added to ICE later, so this function just wasn't updated to check the new flags.

**Comment by GlowPuff** [comment]
I should clarify... the Remove Group action still won't trigger any "on defeated" events or triggers, by design.  This event action was never meant to simulate an actual group defeat.  It's only a mechanism to remove a group from the board.  Similar to "Elvis has left the building".

**Comment by GlowPuff** [comment]
Just one more thing.  In line with what I just said about not simulating an actual group defeat, using Remove Group will also continue to not award any Fame or Imperial Reimbursement from the Adaptive Difficulty option.
