### ISSUE TITLE
Campaign Packager: Story missions allow only core game selection

### ISSUE THREAD

**Issue by Noldorion** [GlowPuff/ICEditor#18]
https://boardgamegeek.com/thread/2611941/article/42470205#42470205

When I create a new campaign in the campaign packager and import it into IC2, I can only select missions from the core game for story missions in the campaign log. Instead of the core game, the campaign log for imported campaigns should allow the selection of missions from the mission pool included in the packaged campaign.

**Comment by GlowPuff** [comment]
Fixed. 🪲
