### ISSUE TITLE
Edit hero skills needs scrolling capabilities

### ISSUE THREAD

**Issue by ristana** [GlowPuff/ICEditor#20]
Entries after the 6th row are impossible to interact with. A scrollbar or window resizer would allow the screen to be worked with
![image](https://github.com/user-attachments/assets/45693b40-e310-4b3a-8226-f289e018367e)

**Comment by GlowPuff** [comment]
Thank you, I'll make a note of this problem.

**Comment by GlowPuff** [comment]
This has been fixed in the latest release.  I'm sorry it took so long - I was in the middle of a move and other things.  Thanks again for letting me know about this issue. 👍🏻
