### ISSUE TITLE
Suggestions: Map Editor

### ISSUE THREAD

**Issue by Noldorion** [GlowPuff/ICEditor#5]
The new Map Editor is amazing! It's intuitive and very easy to use. I have some suggestions that might make it even better.

- It would be great to be able to select multiple tiles from tile gallery at once. Just click on them all, then click "Add" once to have them all added to the map editor.
- Deployment points: We need Yellow and Green color options for the deployment points, those are used a lot in the campaign guides.
- It would be great if one could copy an element. For example, in "Aftermath" I had to place 4 identical terminals. A copy function would have made it a smoother process.
- When I click "Remove" on a map section, please add an "Are you sure?" window. I had to redo an entire section because of a misplaced mouse click 😁

**Comment by GlowPuff** [comment]
Got all these in
