### ISSUE TITLE
Suggestions: Features

### ISSUE THREAD

**Issue by Noldorion** [GlowPuff/ICEditor#6]
Here are some questions and suggestions for features.

- Event triggers: Currently, I can select multiple triggers to trigger an event. However, I'm not sure if those are AND or OR triggers. Ideally, I could select whether ALL the triggers must be fired or whether it is enough if ONE trigger fires. (For example, in the "Rebels lose" event: Rebels lose at the end of Round 6 OR when all heroes are wounded.)
- General Triggers: I'm missing a generic "End of Round" trigger without a specific round counter set, so that we can combine it with other triggers. For example:  "At the end of the round in which the door opens for the first time." This event triggers when two requirements are met: Variable "door_open = 1" and "End of round". I couldn't implement that in the current version of the editor.
- Event groups: Another important feature would be event groups - a group where I can add a couple of events, and when a certain trigger fires, the app randomly picks one of those events to display. This isn't strictly necessary, we can get away with the question prompts, but it would be a more elegant solution. You had those groups in the LotR editor - we basically need exactly the same things.
- Campaign editor: I see you've added a campaign editor button. Do you have any specific ideas for that? I'm not quite sure if we need it, because all the campaign stuff is written down in the printed campaign guides, so selecting single missions should work well enough. But I'm curious if you have cool plans, or if it's just a remnant from the LotR editor.
- One last feature thing: A shortcut to save the mission (for example F5, if you don't want to use STRG+S) would be neat, but not strictly necessary.

**Comment by GlowPuff** [comment]
I got all these in.  Regarding the last one: CTRL+S and F5 saves the mission.  CTRL+L  and F9 to load a mission.
